$lock_cmd = fancylock -l
$suspend_cmd = pidof steam || systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = fancylock -l
}

listener {
    timeout = 180
    on-timeout = fancylock -l
}


